"use client";
import {useState,useEffect,useCallback,useRef,type FormEvent} from 'react';
import {ArrowRight,Check,CheckCircle2,ChevronRight,Clock3,ShieldCheck,BookOpen,Monitor,Users,LockKeyhole,LogOut,RefreshCw,Copy,Maximize,Radio,LoaderCircle,Play,Square,Eye} from 'lucide-react';
import QRCode from 'qrcode';
type Session={id:string;code:string;question:number;phase:string;revision:number;title:string;tag:string;scene:string;prompt:string;options:string[];counts?:number[];total?:number;correct?:number;explanation?:string;action?:string;summaries:{id:number;title:string;tag:string}[]};
const letters=['A','B','C'];
const phaseNames:Record<string,string>={waiting:'等待开题',open:'正在作答',closed:'已收题',revealed:'结果已公布',ended:'课堂已结束'};
async function api(action:string,body?:unknown){const response=await fetch('/api/classroom/'+action,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const r:any=await response.json();if(!response.ok){const e=new Error(r.error??'暂时无法连接，请重试') as Error&{status:number};e.status=response.status;throw e}return r}
function Header({mode}:{mode:string}){return <header className="masthead"><div className="brand"><img src="/brand/logo-white.png" width="353" height="68" alt="重庆科技大学"/><span className="brand-divider"/><span className="brand-name">青廉课堂</span></div><span className="header-label">{mode==='teacher'?'教师控制台':mode==='screen'?'课堂展示':'新生入学教育'}</span></header>}
function Steps({s}:{s:Session|null}){const titles=s?.summaries??[{id:0,title:'班费里的“辛苦费”',tag:'公私分明'},{id:1,title:'评选中的“帮个忙”',tag:'公平办事'},{id:2,title:'竞赛中的“挂个名”',tag:'诚实守信'}];return <section className="journey"><div className="eyebrow">本次课堂 · 三个选择</div>{titles.map(q=><div key={q.id} className={'journey-item '+(s?.question===q.id?'current':'')}><span className="step-number">{s&&s.question>q.id?<Check size={17}/>:String(q.id+1).padStart(2,'0')}</span><div><strong>{q.title}</strong><p>{q.tag}</p></div>{s?.question===q.id&&<ChevronRight size={17}/>}</div>)}<p className="journey-note">认真想一想，再做出你的选择。</p></section>}
function Results({s}:{s:Session}){const total=s.total??0;return <div className="results"><div className="results-heading"><h3>大家的选择</h3><span><b>{total.toLocaleString()}</b> 份回答</span></div>{s.options.map((label,i)=>{const n=s.counts?.[i]??0;const pc=total?Math.round(n/total*100):0;return <div className={'result-row '+(s.correct===i?'correct':'')} key={i}><div className="result-label"><span className="letter">{letters[i]}</span><span>{label}</span>{s.correct===i&&<CheckCircle2 size={18}/>}<strong>{pc}%</strong><small>{n.toLocaleString()} 人</small></div><div className="bar-track"><div style={{width:pc+'%'}}/></div></div>})}{s.explanation&&<div className="explanation"><span><ShieldCheck size={20}/>老师的解析</span><p>{s.explanation}</p><strong>{s.action}</strong></div>}</div>}
export default function Classroom({mode}:{mode:'student'|'teacher'|'screen'}){
 const [code,setCode]=useState('');const [session,setSession]=useState<Session|null>(null);const [joined,setJoined]=useState(false);const [authenticated,setAuthenticated]=useState(false);const [checking,setChecking]=useState(mode==='teacher');const [key,setKey]=useState('');const [selected,setSelected]=useState<number|null>(null);const [submitted,setSubmitted]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [network,setNetwork]=useState('');const [qr,setQr]=useState('');const [joinUrl,setJoinUrl]=useState('');const [notice,setNotice]=useState('');const mounted=useRef(true);const sessionRef=useRef<Session|null>(null);sessionRef.current=session;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const acceptSession=useCallback((s:Session|null)=>{setSession(prev=>prev && s && prev.id===s.id && prev.revision>s.revision?prev:s);if(s)setCode(s.code)},[]);
 const join=useCallback(async(value:string)=>{setBusy(true);setError('');try{const r=await api('join',{code:value});acceptSession(r.session);setJoined(true);history.replaceState(null,'','/?code='+value)}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[acceptSession]);
 useEffect(()=>{const initial=new URLSearchParams(location.search).get('code');if(initial&&/^\d{6}$/.test(initial)){setCode(initial);if(mode==='student')void join(initial);if(mode==='screen')setJoined(true)}if(mode==='teacher'){api('teacher').then(r=>{setAuthenticated(true);acceptSession(r.session)}).catch(e=>{if(e.status!==401)setError(e.message)}).finally(()=>setChecking(false))}},[mode,join,acceptSession]);
 useEffect(()=>{if(!((mode==='teacher'&&authenticated)||(mode!=='teacher'&&joined&&code)))return;let stopped=false;let timer:ReturnType<typeof setTimeout>;let failures=0;async function tick(){try{if(document.visibilityState!=='hidden'){const r=await api(mode==='teacher'?'teacher':'state?code='+code);if(!stopped){acceptSession(r.session);setNetwork('');failures=0}}}catch(e){if(!stopped){setNetwork('连接暂时中断，正在重试；请继续听讲。');failures++;if(mode==='teacher'&&(e as any).status===401){setAuthenticated(false);setSession(null)}}}finally{if(!stopped)timer=setTimeout(tick,Math.min(30000,(mode==='student'?6000:2500)+Math.random()*2000+failures*3000))}}void tick();return()=>{stopped=true;clearTimeout(timer)}},[mode,authenticated,joined,code,acceptSession]);
 useEffect(()=>{setSelected(null);setSubmitted(null);if(mode==='student'&&joined&&session){let current=true;api('mine?code='+session.code).then(r=>{if(current&&r.question===session.question){setSubmitted(r.choice);setSelected(r.choice)}}).catch(()=>{});return()=>{current=false}}},[session?.id,session?.question,joined,mode]);
 useEffect(()=>{if(!session||mode==='student')return;const url=location.origin+'/?code='+session.code;setJoinUrl(url);QRCode.toDataURL(url,{width:240,margin:2,color:{dark:'#55113e',light:'#ffffff'},errorCorrectionLevel:'M'}).then(setQr).catch(()=>setQr(''))},[session?.code,mode]);
 const doAction=async(action:string,body:unknown)=>{setBusy(true);setError('');try{const r=await api(action,body);if(r.session)acceptSession(r.session);return r}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}};
 const login=async(e:FormEvent)=>{e.preventDefault();const r=await doAction('login',{key});if(r){setAuthenticated(true);setKey('')}};
 const control=async(command:string)=>{if(!session)return;if(command==='end'&&!window.confirm('结束本次课堂？结束后学生将无法继续提交。'))return;await doAction('control',{code:session.code,revision:session.revision,command})};
 const submit=async()=>{if(!session||selected===null)return;const q=session.question;const r=await doAction('vote',{code:session.code,question:q,choice:selected});if(r&&sessionRef.current?.id===session.id&&sessionRef.current?.question===q){setSubmitted(r.choice);setSelected(r.choice)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(joinUrl);setNotice('学生链接已复制')}catch{setNotice('复制失败，请复制下方网址')}};
 // Expose read-only classroom state to supporting browser agents.
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_classroom_state',description:'读取当前页面展示的课堂状态，不提交答案或控制课堂。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return {code:session?.code??null,phase:session?.phase??null,question:session?.question??null,submitted:mode==='student'?submitted:null}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[session,submitted,mode]);
 const shown=session&&(mode==='teacher'||session.phase!=='waiting');const revealed=session&&(session.phase==='revealed'||session.phase==='ended');
 return <div className={'app '+mode}><Header mode={mode}/><main className="shell">
 <div className="page-heading"><div><div className="eyebrow">大学第一课 <span>/</span> 廉洁教育</div><h1>让廉洁成为<span>青春底色</span></h1></div>{session?<div className={'phase '+session.phase}><Radio size={16}/>{phaseNames[session.phase]}</div>:<div className="session-label"><BookOpen size={18}/>校园情境互动</div>}</div>
 {network&&<div className="alert" role="status">{network}</div>}{error&&<div className="alert error" role="alert">{error}<button onClick={()=>setError('')} aria-label="关闭提示">×</button></div>}
 <div className="workspace"><div className="main-column">
 {mode==='teacher'&&!authenticated?<section className="card entry"><div className="icon-square"><LockKeyhole/></div><div className="eyebrow">TEACHER</div><h2>准备好，开启一堂好课。</h2><p className="intro">开放题目、查看回答，和同学们一起讨论每一次选择。</p><form onSubmit={login}><label htmlFor="teacher-key">教师口令</label><input id="teacher-key" type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)} placeholder="请输入活动负责人提供的口令" required/><button className="primary" disabled={busy||checking||!key}>{busy||checking?<LoaderCircle className="spin" size={19}/>:<LockKeyhole size={18}/>}进入教师控制台</button></form><a className="text-link" href="/">返回学生入口 <ArrowRight size={15}/></a></section>:
 mode==='student'&&!joined?<section className="card entry"><div className="entry-top"><div className="icon-square"><BookOpen/></div><span className="mini-label">同上一堂课 · 共作一个选择</span></div><h2>你的大学，从每一次选择开始。</h2><p className="intro">输入老师展示的课堂码，参与今天的三个校园情境。</p><form onSubmit={e=>{e.preventDefault();void join(code)}}><label htmlFor="class-code">六位课堂码</label><input className="code-input" id="class-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="off" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" required/><button className="primary" disabled={busy||code.length!==6}>{busy?<LoaderCircle className="spin" size={20}/>:null}进入课堂 <ArrowRight size={19}/></button></form><div className="privacy-note"><ShieldCheck size={17}/><span>无需填写姓名、学号 · 不设个人排名</span></div></section>:
 mode==='screen'&&!session?<section className="card entry"><Monitor size={36}/><h2>连接课堂展示</h2><form onSubmit={e=>{e.preventDefault();setJoined(true)}}><label htmlFor="screen-code">课堂码</label><input id="screen-code" value={code} maxLength={6} inputMode="numeric" onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button className="primary" disabled={code.length!==6}>连接课堂</button></form></section>:
 mode==='teacher'&&authenticated&&!session?<section className="card entry"><div className="icon-square"><Play/></div><h2>今天的课堂，准备开始。</h2><p className="intro">创建课堂后，将生成学生入口二维码和六位课堂码。</p><button className="primary" disabled={busy} onClick={()=>doAction('create',{})}>创建课堂 <ArrowRight size={18}/></button><p className="hint">内含三个校园情境，每题由你控制开放与收题。</p></section>:
 session&&!shown?<section className="card waiting"><div className="waiting-symbol"><Clock3 size={34}/></div><div className="eyebrow">情境 {String(session.question+1).padStart(2,'0')} / 03</div><h2>{session.question===0?'已进入课堂，等老师开题。':'下一次选择，即将开始。'}</h2><p>请先听老师讲述情境，题目开放后会自动显示。</p><div className="waiting-code">课堂码 <strong>{session.code}</strong></div><span className="hint">保持页面打开，无需反复刷新</span></section>:
 session?<section className="card question-card"><div className="question-top"><span className="eyebrow">情境 {String(session.question+1).padStart(2,'0')} <span>/ 03</span></span><span className="topic">{session.tag}</span></div><h2>{session.title}</h2>{!(mode==="screen"&&revealed)&&<><p className="scene">{session.scene}</p><div className="question-divider"/></>}<h3>{session.prompt}</h3>
 {revealed?<Results s={session}/>:<div className="options" role={mode==='student'?'radiogroup':undefined} aria-label="请选择你的回答">{session.options.map((label,i)=><button key={i} type="button" className={'option '+(selected===i?'selected ':'')+(submitted===i?'submitted':'')} role={mode==='student'?'radio':undefined} aria-checked={mode==='student'?selected===i:undefined} disabled={mode!=='student'||session.phase!=='open'||submitted!==null||busy} onClick={()=>setSelected(i)}><span className="letter">{letters[i]}</span><span>{label}</span><span className="choice-marker">{selected===i&&<Check size={16}/>}</span></button>)}</div>}
 {mode==='student'&&!revealed&&<div className="answer-footer" aria-live="polite">{submitted!==null?<div className="success-message"><CheckCircle2 size={22}/><div><strong>已提交，选择 {letters[submitted]}</strong><p>请继续听讲，等待老师公布结果。</p></div></div>:session.phase==='open'?<><button className="primary" disabled={busy||selected===null} onClick={submit}>{busy?<LoaderCircle className="spin" size={19}/>:null}确认提交 {selected!==null&&letters[selected]}<ArrowRight size={18}/></button><p className="hint">每题提交一次，提交后不可修改。</p></>:<p className="hint">{session.phase==='closed'?'本题已收题，请等待老师公布结果。':'老师尚未开放本题，请先阅读情境。'}</p>}</div>}
 {session.phase==='ended'&&<div className="finished"><CheckCircle2 size={22}/><div><strong>本次课堂已结束，感谢你的参与。</strong><p>把公私分明、公平与诚信，带进大学生活。</p></div></div>}
 </section>:<section className="card waiting"><LoaderCircle className="spin"/><h2>正在连接课堂…</h2></section>}
 {mode==='teacher'&&authenticated&&session&&<section className="card control-panel"><div><span className="eyebrow">课堂控制</span><p>先收题，再向学生公布结果。</p></div><div className="control-buttons">{session.phase==='waiting'&&<button className="primary" disabled={busy} onClick={()=>control('open')}><Play size={18}/>开放本题</button>}{session.phase==='open'&&<button className="primary" disabled={busy} onClick={()=>control('close')}><Square size={17}/>结束作答</button>}{session.phase==='closed'&&<button className="primary" disabled={busy} onClick={()=>control('reveal')}><Eye size={18}/>公布结果与解析</button>}{session.phase==='revealed'&&session.question<2&&<button className="primary" disabled={busy} onClick={()=>control('next')}>准备下一题 <ArrowRight size={18}/></button>}{session.phase!=='ended'&&<button className="secondary" disabled={busy} onClick={()=>control('end')}>结束课堂</button>}{session.phase==='ended'&&<button className="primary" disabled={busy} onClick={()=>doAction('create',{})}>创建新课堂</button>}</div></section>}
 {mode==='teacher'&&session&&!revealed&&<section className="card live-counts"><Results s={session}/><p className="hint">当前统计仅教师可见，学生端将在公布后显示。</p></section>}
 </div><aside className="side-column">
 {session&&mode!=='student'&&<section className="card join-card"><div className="eyebrow">扫码参与课堂</div>{qr&&<img src={qr} width="200" height="200" alt="学生加入本次课堂的二维码"/>}<p>或输入课堂码</p><strong className="big-code">{session.code}</strong>{mode==='teacher'&&<><button className="secondary" onClick={copy}><Copy size={16}/>复制学生链接</button><a className="secondary" href={'/screen?code='+session.code} target="_blank" rel="noreferrer"><Monitor size={17}/>打开课堂展示</a><p className="url-line">{joinUrl}</p><span className="hint" role="status">{notice}</span></>}</section>}
 <Steps s={session}/>{mode==='student'&&<section className="side-note"><ShieldCheck size={22}/><h3>选择之后，更要想一想。</h3><p>这里没有个人排名。每个情境都是一次练习，帮助我们学会负责任地做选择。</p></section>}
 {mode==='teacher'&&<section className="side-note"><Monitor size={22}/><h3>直播时共享“课堂展示”</h3><p>控制台供教师操作。向学生直播展示页，可避免提前公开统计结果。</p></section>}
 </aside></div>
 <footer className="footer"><span>重庆科技大学 · 新生廉洁教育</span><div>{mode==='student'?<a href="/teacher">教师入口 <ChevronRight size={14}/></a>:mode==='teacher'?<><a href="/">学生入口</a>{authenticated&&<button onClick={async()=>{const r=await doAction('logout',{});if(r){setAuthenticated(false);setSession(null)}}}><LogOut size={14}/>退出</button>}</>:<button onClick={()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>setError('当前浏览器不支持全屏'))}><Maximize size={16}/>全屏展示</button>}</div></footer>
 </main></div>
}




